### PR TITLE
refactor: enable strictPropertyInitialization

### PR DESCRIPTION
**Pull request by zthaver**
Addressed the strictPropertyInitialization task in #32 

Initialized variable and added the assignment assertion operator to support strictPropertyInitialization.

### CODE REVIEW

**Review by pynnl — APPROVED** [review]

**Review by poftadeh — CHANGES_REQUESTED** [review]
The `!` is asserting that these properties are not undefined, but in actuality they are. Changing the type to include `undefined` instead will satisfy the strict check and more accurately reflect what is happening (e.g. `dom: JSDOM | undefined` rather than `dom!: JSDOM`).

**Comment by zthaver** [comment]
> The `!` is asserting that these properties are not undefined, but in actuality they are. Changing the type to include `undefined` instead will satisfy the strict check and more accurately reflect what is happening (e.g. `dom: JSDOM | undefined` rather than `dom!: JSDOM`).

But if I made dom JSDOM | undefined, with the strictNullChecks, it will give errors, saying that dom is possibly undefined.

**Comment by pynnl** [comment]
> 
> 
> The `!` is asserting that these properties are not undefined, but in actuality they are. Changing the type to include `undefined` instead will satisfy the strict check and more accurately reflect what is happening (e.g. `dom: JSDOM | undefined` rather than `dom!: JSDOM`).

I think since those properties are initialized in the constructor, we can safely say they are not `undefined`. The reason it yields error with `strictPropertyInitialization` is that they are not defined **directly** in constructor. [TS website](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#strict-class-initialization) also suggests using `!` operator in this case.

**Review by poftadeh — APPROVED** [review]
> TS website also suggests using ! operator in this case.

I'm also a bit cautious about opting out of type checking, but if this is the recommended best practice for helper methods, then that sounds good to me.

**Review by manekenpix — APPROVED** [review]

**Pull request merged**
